### ISSUE TITLE
speedup due to state reuse, compared by 2 32seq_len+state-reuse vs 1 64seq_len+no-state-reuse?

### ISSUE THREAD

**Issue by guotong1988** [kimiyoung/transformer-xl#41]
预测速度快是因为state reuse？是用 两个32seq_len+state-reuse 和 一个64seq_len+no-state-reuse 比吗？
![image](https://user-images.githubusercontent.com/4702353/53218604-be2b9680-3697-11e9-84a7-19117cc9de03.png)

多谢多谢多谢！
@kimiyoung 
@zihangdai

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/53457969-2e0e9800-3a6f-11e9-98b9-faf92eca3c20.png)

**Comment by kimiyoung** [comment]
For vanilla Transformer language models (Al Rfou et al), you process [1 2 3 4], predict 5, process [2 3 4 5], predict 6, and repeat.
For a Transformer-XL language model, you process [1 2 3 4], predict [5 6 7 8], predict [9 10 11 12], and repeat. Note that we don't have to reprocess [5 6 7 8] when predicting [9 10 11 12], because the representations can be reused.
There are a few GIFs [here](https://ai.googleblog.com/2019/01/transformer-xl-unleashing-potential-of.html) that might give you more understanding.

**Comment by guotong1988** [comment]
Thank you very much!
